version: 0.2

phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.7/2024-12-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - TAG="$IMAGE_TAG.$(date +%Y-%m-%d.%H.%M.%S)"
      - sudo yum update -y
      - sudo yum install git -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG
      - echo "Create temporary folder to clone the repo into..."
      - TEMP_FOLDER="$(mktemp -d)"
      - echo "Clone the repository..."
      - git clone -b master "https://ahuja012002:${GITHUB_TOKEN}@github.com/ahuja012002/AWS-Springboot-3tierApp.git" ${TEMP_FOLDER}
      - cd ${TEMP_FOLDER}
      - sed -i 's+215472211497.dkr.ecr.us-east-1.amazonaws.com/devops-repo-testing.*+'"215472211497.dkr.ecr.us-east-1.amazonaws.com/devops-repo-testing:$TAG"'+g' hello-k8s.yaml
      - git config --system --add safe.directory '*'
      - git config user.name “ahuja012002”
      - git config user.email “ahuja012002@yahoo.co.in”
      - git add .
      - git commit -m "sample commit"
      - git push -u origin master
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG
